config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#splash'
  resources :categories do
    resources :purchases, only: [:new, :show]
  end
  resources :purchases, except: [:new, :show, :index]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # Associations
  belongs_to :user
  has_and_belongs_to_many :purchases

  # Methods

  # Validations
  validates :name, presence: true
  validates :icon, presence: true

  # Callbacks
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories

  validates :name, presence: true
  validates :amount, presence: true
  validates :categories, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :purchases

  attribute :name, :string

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      categories_path
      categories_path
    else
      super
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]
  def index
    @categories = current_user.categories.includes(:purchases)
  end

  def show
    @purchases = @category.purchases.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        handle_uploaded_icon_file if category_params[:icon].present?
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        handle_uploaded_icon_file if category_params[:icon].present?
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def handle_uploaded_icon_file
    uploaded_file = category_params[:icon]
    file_path = Rails.root.join('public', 'uploads', uploaded_file.original_filename)

    File.binwrite(file_path, uploaded_file.read)

    @category.update(icon: File.join('/uploads', uploaded_file.original_filename))
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_purchase, only: %i[show edit update destroy]

  def index
    @purchases = Purchase.all
  end

  def show; end

  def new
    @attributes = []
    @purchase = Purchase.new
    @attributes << @purchase
    @categories = current_user.categories
    @attributes << @categories
  end

  def edit
    @attributes = []
    @attributes << @purchase
    @categories = current_user.categories
    @attributes << @categories
  end

  def create
    @attributes = []
    @purchase = Purchase.new(purchase_params)
    @purchase.author = current_user
    category_id = params[:purchase][:category_id]
    if category_id.present?
      category = Category.find(category_id)
      @purchase.categories << category
    end
    @attributes << @purchase
    @categories = current_user.categories
    @attributes << @categories

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to category_url(@purchase.categories[0]), notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to purchase_url(@purchase), notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_purchase
    @purchase = Purchase.find(params[:id])
  end

  def purchase_params
    params.require(:purchase).permit(:name, :amount)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def splash; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="drop-shadow-md bg-white flex justify-start gap-5 w-full p-3">
  <div class="w-2/12 flex flex-col justify-between">
    <% if category.icon.present? %>
        <%= image_tag category.icon, alt: category.name, class: 'w-16 rounded' %>
    <% end %>
  </div>
  <div class="w-10/12 flex flex-col justify-between">
    <div class="flex justify-between w-full">
      <p class="text-gray-400 font-bold"><%= category.name %></p>
      <p class="self-center text-gray-700 font-bold">Total: $<%= category.purchases.sum(:amount) %></p>
    </div>
    
    <p class="text-gray-300 text-xs">
    <span><%= category.created_at.strftime('%d %b %Y') %></span>
    </p>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: 'mt-10 flex flex-col gap-5 p-4') do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block mb-2" %>
    <%= form.text_field :name, class: 'w-full  border-none' %>
  </div>
  
  <div>
    <%= form.label :your_attribute, class: "mb-2 inline-block" do %>
      Icon
    <% end %>
    
    <%= form.file_field :icon, id: 'icon_upload', class: "relative m-0 block w-full min-w-0 flex-auto rounded border border-solid border-neutral-300 bg-clip-padding px-3 py-[0.32rem] text-base font-normal text-neutral-700 transition duration-300 ease-in-out file:-mx-3 file:-my-[0.32rem] file:overflow-hidden file:rounded-none file:border-0 file:border-solid file:border-inherit file:bg-neutral-100 file:px-3 file:py-[0.32rem] file:text-neutral-700 file:transition file:duration-150 file:ease-in-out file:[border-inline-end-width:1px] file:[margin-inline-end:0.75rem] hover:file:bg-neutral-200 focus:border-primary focus:text-neutral-700 focus:shadow-te-primary focus:outline-none dark:border-neutral-600 dark:file:bg-neutral-700 dark:file:text-neutral-100", id: "formFile" %>
  </div>

  <div>
    <%= form.submit "Save", class: 'mt-6 p-3 px-5 bg-green-800 text-white hover:bg-green-600 w-full' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="navigation py-6 px-3 blue-nav-white-text">
      <ul class="flex justify-between items-center">
        <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), category_path(@category), class: 'nav-link' %></li>
        <h2><strong>Editing category</strong></h2>
        <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
      </ul>
    </div>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<div class="flex flex-col h-screen justify-between">
  <div>
    <div class="navigation py-6 px-3 blue-nav-white-text">
      <ul class="flex justify-between items-center">
        <li class="w-10">
          <%= link_to image_tag('backarrow.png', alt: 'Back'), root_path, class: 'nav-link' %>
        </li>
        <h2><strong>Categories</strong></h2>
        <li>
          <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
        </li>
      </ul>
    </div>

    <section class="">
      <p class="text-green-500"><%= notice %></p>

      <div id="categories">
        <% @categories.each do |category| %>
          <a href="<%= category_path(category) %>" class="space-y-1 mt-1 border-gray-400">
            <%= render category %>
          </a>
        <% end %>
      </div>
    </section>
  </div>

  <section class="text-center">
    <%= link_to new_category_path do %>
      <div class="w-full bg-lime-600 flex text-white">
        <button class="font-bold p-2 py-4 m-4 text-lg w-full border-2 bg-lime-600 rounded hover:bg-lime-500 focus:outline-none focus:bg-lime-500">
          Add a New Category 
        </button>
      </div>
    <% end %>
  </section>
</div>

app/views/categories/new.html.erb
<div class="navigation py-6 px-3 blue-nav-white-text">
  <ul class="flex justify-between items-center">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), categories_path, class: 'nav-link' %></li>
    <h2><strong>New category</strong></h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<div class="flex flex-col h-screen justify-between">
  <div>
    <div class="navigation py-6 px-3 blue-nav-white-text">
      <ul class="flex justify-between items-center">
        <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), categories_path, class: 'nav-link' %></li>
        <h2><strong><%= @category.name %></strong></h2>
        <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
      </ul>
    </div>
    <p style="color: green"><%= notice %></p>

    <%= render @category %>
    <section class="px-5">
      <div id="purchases">
        <% @purchases.each do |purchase| %>
          <a href="<%= category_purchase_path(@category, purchase) %>" class="m-1">
          <%= render "purchases/purchase", purchase: purchase %>
          </a>
        <% end %>
      </div>
    </section>
  </div>

  <section class="flex flex-col space-y-2 p-5">
      <%= link_to 'New purchase', new_category_purchase_path(@category), class:"text-center p-3 px-5 bg-green-800 text-white hover:bg-green-600 w-full focus:outline-none focus:bg-green-600" %>
      <%= link_to 'Edit category', edit_category_path(@category), class:"text-center p-3 px-5 bg-yellow-800 text-white hover:bg-yellow-600 w-full focus:outline-none focus:bg-green-600" %>

      <%= button_to "Delete category", @category, method: :delete, data: { confirm: 'Are you sure?' }, class: "p-3 px-5 bg-red-800 text-white hover:bg-red-600 w-full" %>
    </section>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="newcustom mx-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_with(model: attributes[0], local: true, class: 'mt-10 flex flex-col gap-5 p-4') do |form| %>
  <% if attributes[0].errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attributes[0].errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% attributes[0].errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'w-full  border-none' %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount, class: 'w-full  border-none' %>
  </div>

  <div>
    <%= form.label :category, style: "display: block", class: 'invisible' %>
    <%= form.collection_select :category_id, attributes[1], :id, :name, { prompt: 'Choose category.....' }, class: 'w-full  border-none'%>
  </div>

  <div>
    <%= form.submit "Save", class: 'text-center p-3 px-5 bg-green-800 text-white hover:bg-green-600 w-full focus:outline-none focus:bg-green-600' %>
  </div>
<% end %>

app/views/purchases/_purchase.html.erb
<div id="<%= dom_id purchase %>" class="drop-shadow-md bg-white flex w-full p-3 rounded justify-between">
<div>
  <p>
    <strong><%= purchase.name %></strong>
  </p>

  <p class="text-gray-400 text-xs">
    <span><%= purchase.created_at.strftime('%d %b %Y') %></span>
  </p>
</div>
  
  <p class="text-gray-700">
    $<%= purchase.amount %>
  </p>

</div>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render "form", attributes: @attributes %>

<br>

<div>
  <%= link_to "Show this purchase", @purchase %> |
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Purchases</h1>

<div id="purchases">
  <% @purchases.each do |purchase| %>
    <%= render purchase %>
    <p>
      <%= link_to "Show this purchase", purchase %>
    </p>
  <% end %>
</div>

<%#= link_to "New purchase", new_purchase_path %>

app/views/purchases/new.html.erb
<div class="navigation py-6 px-3 blue-nav-white-text">
  <ul class="flex justify-between items-center">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), categories_path, class: 'nav-link' %></li>
    <h2><strong>New purchase</strong></h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>

<%= render "form", attributes: @attributes %>

app/views/purchases/show.html.erb
<div class="navigation py-6 px-3 blue-nav-white-text">
  <ul class="flex justify-between items-center">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), category_path(@purchase.categories[0]), class: 'nav-link' %></li>
    <h2><strong>Show purchase</strong></h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>
<p style="color: green"><%= notice %></p>

<div class="flex flex-col bg-white p-5 drop-shadow-md">
  <p class="flex justify-between py-2">
    <span><strong>Name:</strong></span>
    <span><%= @purchase.name %></span>
  </p>
  <p class="border-y-4 py-2 flex justify-between">
    <span><strong>Amount:</strong></span>
    <span>$<%= @purchase.amount %></span>
  </p>
  <p class="border-b-4 py-2 flex justify-between">
    <span><strong>Categories:</strong></span>
    <span><%= @purchase.categories[0].name %></span>
  </p>
  <p class="py-2 flex justify-between">
    <span><strong>Created at:</strong></span>
    <span><%= @purchase.created_at %></span>
  </p>
</div>

<div>
  <%= button_to "Delete", @purchase, method: :delete, class: "mt-5 ms-5 p-3 px-5 red-btn text-white rounded-md hover:bg-red-600 focus:outline-none focus:bg-red-600 drop-shadow-md" %>
</div>

app/views/static_pages/splash.html.erb
<div class="flex flex-col justify-between h-screen items-center">
  <p class="text-center p-3 py-5 blue-btn w-full">Welcome to Budget Monitor</p>
  <a href="<%= categories_path %>" class="w-full text-center text-3xl blue font-bold">Spew Budgeter</button></a>
  <div class="w-full">
      <div class="flex flex-col w-full space-y-3 px-4">
        <% if user_signed_in? %>
            <a href="<%= categories_path %>" class="w-full blue-btn text-center p-4 border-s-2 hover:bg-gray-300 hover:text-black">View categories</button></a>
        <% else %>
          <%= link_to 'Sign In', new_user_session_path, class:"w-full blue-btn text-center p-4 border-s-2 hover:bg-gray-300 hover:text-black" %>
          <%= link_to 'Sign Up', new_user_registration_path, class:"w-full blue-btn text-center p-4 border-s-2 hover:bg-gray-300 hover:text-black" %>
        <% end %>
      </div>
  </div>
</div>